# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-19 03:47
from __future__ import unicode_literals

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models
import utils.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('sex', utils.models.MyCharField(default='保密', max_length=3, verbose_name='性别')),
                ('username', models.CharField(default=utils.shortcuts.default_username, max_length=50, verbose_name='用户名')),
                ('user_id', models.CharField(default=utils.shortcuts.default_user_id, max_length=20, unique=True, verbose_name='用户编号')),
                ('email', utils.models.MyCharField(db_index=True, max_length=50, null=True, unique=True, verbose_name='邮箱')),
                ('phone', utils.models.MyCharField(default='', max_length=15, null=True, verbose_name='手机号')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='注册时间')),
                ('description', models.CharField(default='', max_length=60, verbose_name='个人描述')),
                ('admin_type', models.CharField(default='Regular User', max_length=20, verbose_name='用户类型')),
                ('problem_permission', models.CharField(default='None', max_length=10, verbose_name='修改问题权限')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='是否可用')),
                ('is_login', models.BooleanField(default=False, verbose_name='是否登录')),
                ('is_auth', models.BooleanField(default=False, verbose_name='是否认证')),
                ('is_email_auth', models.BooleanField(default=False, verbose_name='邮箱是否被验证')),
                ('register_type', models.CharField(default='normal', max_length=20, verbose_name='用户注册类型')),
                ('session_keys', utils.models.MyJSONField(default=list)),
            ],
            options={
                'db_table': 'user',
                'ordering': ('-create_time',),
            },
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('teacher', models.CharField(default='', max_length=10, verbose_name='班主任')),
                ('level', models.CharField(default='', max_length=6, verbose_name='年级')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('department', models.CharField(default='', max_length=20, verbose_name='院系')),
                ('edu_level', models.CharField(default='', max_length=4, verbose_name='学历层次')),
                ('class_id', models.SmallIntegerField(default=1, verbose_name='班号')),
                ('stu_number', models.SmallIntegerField(default=0, verbose_name='学生数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'grade_info',
            },
        ),
        migrations.CreateModel(
            name='OwnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='', max_length=20, verbose_name='学院名称')),
                ('d_code', models.CharField(default='', max_length=10, verbose_name='学院代码')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('m_code', models.CharField(default='', max_length=10, verbose_name='专业代码')),
            ],
            options={
                'db_table': 'own_info',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(default='', max_length=10, verbose_name='真实姓名')),
                ('avatar', models.CharField(default='/public/avatar/default.png', max_length=40, verbose_name='头像路径')),
                ('school', models.CharField(default='中国石油大学胜利学院', max_length=20, verbose_name='学校')),
                ('class_id', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='class_id')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('level', models.CharField(default='', max_length=6, verbose_name='年级')),
                ('edu_level', models.CharField(default='', max_length=5, verbose_name='学历层次')),
                ('department', models.CharField(default='', max_length=20, verbose_name='院系')),
                ('acm_problems_status', utils.models.MyJSONField(default=dict, verbose_name='ACM 进度')),
                ('oi_problems_status', utils.models.MyJSONField(default=dict, verbose_name='IO 进度')),
                ('collect_problem', utils.models.MyJSONField(default=list, verbose_name='试题收藏记录')),
                ('accepted_number', models.IntegerField(default=0, verbose_name='解决问题数量')),
                ('total_score', models.BigIntegerField(default=0, verbose_name='得分')),
                ('submission_number', models.IntegerField(default=0, verbose_name='提交次数')),
                ('qq', models.PositiveIntegerField(default=0, verbose_name='QQ号')),
                ('github', models.CharField(default='', max_length=40, verbose_name='GitHub账号')),
                ('webchat', models.CharField(default='', max_length=40, verbose_name='微信号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=0, verbose_name='user_id')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(null=True)),
                ('ip', models.CharField(default='', max_length=15)),
                ('sys', models.CharField(default='', max_length=50)),
                ('session_key', models.CharField(db_index=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'user_record',
                'ordering': ('-login_time',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Grade', verbose_name='班级ID'),
        ),
    ]
