# Generated by Django 2.1.7 on 2020-01-10 10:12

from django.db import migrations, models
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_adminoperationrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=True, verbose_name='是否点赞')),
                ('liked_id', models.PositiveIntegerField(default=0, verbose_name='被点赞对象的id')),
                ('user_id', models.PositiveIntegerField(default=0, verbose_name='用户id')),
                ('liked_obj', utils.models.MyCharField(default='', max_length=8, verbose_name='点赞的对象')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('up_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='取消时间')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
    ]
