# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-19 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', utils.models.MyCharField(max_length=40, unique=True, verbose_name='键')),
                ('value', utils.models.MyJSONField(verbose_name='值')),
            ],
            options={
                'db_table': 'sys_options',
            },
        ),
    ]
