# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-31 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsubmission',
            name='user_id',
            field=models.PositiveIntegerField(default=0, verbose_name='用户id'),
        ),
    ]
