# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20191026_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
    ]
