# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-12-17 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0003_announcements_is_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='created_by',
            field=models.CharField(default='admin', max_length=12, verbose_name='创建者姓名'),
        ),
    ]
