# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-12-28 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_auto_20191217_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='view_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
