# Generated by Django 2.1.7 on 2020-01-17 09:51

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_announcements_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=utils.models.MyJSONField(default=dict, verbose_name='消息体'),
        ),
    ]
