# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-06 12:52
from __future__ import unicode_literals

from django.db import migrations, models

import utils.models


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='has_problem_list',
            field=utils.models.MyJSONField(default=dict, verbose_name='已经导入的试题'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='s_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='考试人数'),
        ),
    ]
