# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-26 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_contestofgrade_is_contest'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='acmcontestrank',
            index_together=set([('user_id', 'contest_id')]),
        ),
    ]
