# Generated by Django 2.1.7 on 2020-01-17 09:51

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0005_contestannouncement_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestannouncement',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 17, 9, 51, 23, 355977, tzinfo=utc)),
        ),
    ]
