# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-06 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    # operations = [
    #     migrations.AlterIndexTogether(
    #         name='contestproblem',
    #         index_together=set([]),
    #     ),
    # ]
