# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-06 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20191006_1252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together=set([]),
        ),
    ]
