# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-12-13 11:27
from __future__ import unicode_literals

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20191023_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='template',
            field=utils.models.MyJSONField(default=[], verbose_name='模板'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=utils.models.MyJSONField(default=[], verbose_name='模板'),
        ),
    ]
