# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-09-19 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=245)),
                ('uid', models.IntegerField(default=0)),
                ('user_contact', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'advice_info',
            },
        ),
        migrations.CreateModel(
            name='BugCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_type', models.CharField(default='', max_length=10)),
                ('bug_contest', models.CharField(default='', max_length=200)),
                ('bug_location', models.CharField(default='', max_length=20)),
                ('bug_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('bug_uid', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'bugs_info',
            },
        ),
        migrations.CreateModel(
            name='DailyInfoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_count', models.PositiveSmallIntegerField(verbose_name='一天提交数量')),
                ('con_count', models.PositiveSmallIntegerField(verbose_name='一天竞赛创建数量')),
                ('accept_count', models.PositiveSmallIntegerField(verbose_name='一天的提交正确数量')),
                ('active_count', models.PositiveSmallIntegerField(verbose_name='一天的活跃用户数量')),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_info_status',
                'ordering': ('create_time',),
            },
        ),
        migrations.CreateModel(
            name='JudgeServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', utils.models.MyCharField(default='', max_length=15, verbose_name='judge主机')),
                ('ip', utils.models.MyCharField(default='', max_length=16, verbose_name='judgeIP')),
                ('judger_version', utils.models.MyCharField(default='', max_length=10, verbose_name='judge版本')),
                ('cpu_core', models.IntegerField(verbose_name='cup核数')),
                ('memory_usage', models.FloatField()),
                ('cpu_usage', models.FloatField()),
                ('last_heartbeat', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('task_number', models.IntegerField(default=0)),
                ('service_url', utils.models.MyCharField(default='', max_length=35, verbose_name='judge地址')),
                ('is_disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'judge_server',
            },
        ),
    ]
