# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-07 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20191006_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugcollections',
            name='bug_error_api',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='bugcollections',
            name='bug_contest',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AlterField(
            model_name='bugcollections',
            name='bug_location',
            field=models.CharField(default='', max_length=65),
        ),
        migrations.AlterField(
            model_name='bugcollections',
            name='bug_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
