# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-26 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_auto_20191007_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugcollections',
            name='bug_finder',
            field=models.CharField(default='', max_length=15),
        ),
    ]
