# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-30 05:09
from __future__ import unicode_literals

from django.db import migrations
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_bugcollections_bug_finder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeserver',
            name='service_url',
            field=utils.models.MyCharField(default='', max_length=70, verbose_name='judge地址'),
        ),
    ]
